### ISSUE TITLE
TypeError: options.imageSource.saveToFile is not a function

### ISSUE THREAD

**Issue by lord-zeus** [PeterStaev/nativescript-photo-editor#13]
passing the image and its not finding the saveToFile function 

TypeError: options.imageSource.saveToFile is not a function

**Comment by PeterStaev** [comment]
Problem is the same as your other issue. Make sure you are using the plugin as explained in readme and as demonstrated in the demo app in this repo.

**Comment by lord-zeus** [comment]
`const photoEditor = new PhotoEditor();
               let imageSource = fromFileOrResource('~/assets/images/logo.png');

             console.log("ORIG IMAGE: ", imageSource.height, imageSource.width)

              photoEditor.editPhoto({
                    imageSource: imageSource.android, // originalImage.imageSource,
                
              }).then((newImage) => {
                   console.log("NEW IMAGE: ", newImage.height, newImage.width)
               }).catch((e) => {
                 `   console.error(e);

                });`

this is my code 

and the console is : 
`'ORIG IMAGE: ' 252 269`
`TypeError: options.imageSource.saveToFile is not a function`

**Comment by PeterStaev** [comment]
Hey @lord-zeus , 
Per the docs and demos you should send the image source to the plugin not the native object like you do. So the correct code should be something like:
```ts
const photoEditor = new PhotoEditor();
let imageSource = fromFileOrResource('~/assets/images/logo.png');

console.log("ORIG IMAGE: ", imageSource.height, imageSource.width)

photoEditor.editPhoto({
	imageSource,            
}).then((newImage) => {
	console.log("NEW IMAGE: ", newImage.height, newImage.width)
}).catch((e) => {
	console.error(e);
});
```

**Comment by max-pro** [comment]
fromFileOrResource function is not defined. what we need to import

**Comment by PeterStaev** [comment]
@max-pro , it is from the `image-source` nativescript module: https://docs.nativescript.org/api-reference/modules/_image_source_

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.

**Comment by max-pro** [comment]
How to save image. Save function is undefined
