### ISSUE TITLE
TypeError: Cannot read property 'photoeditor' of undefined

### ISSUE THREAD

**Issue by JasonMan34** [PeterStaev/nativescript-photo-editor#15]
When trying to use the module, it doesn't work and the error message I get is
`TypeError: Cannot read property 'photoeditor' of undefined`

The (relevant) code:
```
import {PhotoEditor, PhotoEditorControl} from "../nativescript-photo-editor";
import {fromFileOrResource} from "image-source";

let image = fromFileOrResource(this.imagePath); // "/storage/.../IMG-0001.jpg"

const photoEditor = new PhotoEditor();
photoEditor.editPhoto({
    imageSource: image
})
.then(newImage => {
    console.log(newImage);
    // resultImage.imageSource = newImage;
})
.catch(e => {
    console.error(e);
});
```

**Comment by PeterStaev** [comment]
Hey @JasonMan34 , your import paths are a bit strange as they are relative. Please take a look at the attached demo in this repo and also take a look at the Readme to see how to use the plugin.

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.
