### ISSUE TITLE
`iOSPhotoEditor` does not specify a Swift version

### ISSUE THREAD

**Issue by relez** [PeterStaev/nativescript-photo-editor#16]
Hi there, I am having this error when I try to build the app for iOS.

`[19-03-06 16:22:39.246] (CLI) - `iOSPhotoEditor` does not specify a Swift version and none of the targets (`MyAppName`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.`

Any clue?

**Comment by PeterStaev** [comment]
Hey @relez , I have not seen this error with this plugin itself. But I see there are other users reporting problems with Swift pods. You can check [this thread on SO](https://stackoverflow.com/questions/53009550/swift-version-nativescript) for possible resolutions.

**Comment by relez** [comment]
Hu @PeterStaev, I was able to compile the app downgrading cocoapods to 1.5.3, but I got this warnings so might be helpful for the future:

```
warning: Swift 3 mode has been deprecated and will be removed in a later version of Xcode. Please migrate "iOSPhotoEditor" to Swift 4.2 using "Convert > To Current Swift Syntax…" in the Edit menu. (in target 'iOSPhotoEditor')
warning: Swift 3 mode has been deprecated and will be removed in a later version of Xcode. Please migrate "iOSPhotoEditor" to Swift 4.2 using "Convert > To Current Swift Syntax…" in the Edit menu. (in target 'iOSPhotoEditor')
```
My problem is that I can not  build using Sidekick on the cloud because I cant downgrade the cocoapods version on the server, I hope there is a fix in the code for this.

Thanks!

**Comment by throwingdarts** [comment]
@PeterStaev I am having the same issue after upgrading iOS SDK now required by Apple. How do we downgrade cocoapods when we have to cloud build from a windows machine? I did find [this](https://github.com/NativeScript/sidekick-feedback/issues/259) about installing a plugin which did not work in my case.

**Comment by PeterStaev** [comment]
Guys, I'm working on updating the pod code from the upstream branch which makes the code Swift 4.2 compatible so it should fix these problems. Will let you know once the new version is on npm.

**Comment by throwingdarts** [comment]
Thank you @PeterStaev , it's holding up my ability to publish at the moment.

**Comment by PeterStaev** [comment]
New version on npm should resolve this problem.
