### ISSUE TITLE
How to use photoEditorSDK.saveImage(folderName, imageName);

### ISSUE THREAD

**Issue by shinde-sagar** [PeterStaev/nativescript-photo-editor#17]
I want to save file after edit to folder

**Comment by PeterStaev** [comment]
Hey @shinde-sagar , no need to use the SDK native methods. The plugin already returns an `ImageSource` object which you can save with one of the provided methods: https://docs.nativescript.org/ns-framework-modules/image-source#save-image

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.
