### ISSUE TITLE
Not compatible with latest ns version -> short import to correct

### ISSUE THREAD

**Issue by Serge-SDL** [PeterStaev/nativescript-photo-editor#24]
Hi!

the plugin is no more compatible with last ns version because it has a short import of image-source on photo-editor.d.ts -> can you just change 
`import { ImageSource } from "image-source";`
to
`import { ImageSource } from "tns-core-modules/image-source";`

thanks!

**Comment by PeterStaev** [comment]
Hey @Serge-SDL , I  am aware that the {N} core team is depreciating those short import paths and are pushing all devs to write the full path which seems ridiculous as you have to type an additional 31 symbols for every import. You can read more details on the suggestions here: https://github.com/NativeScript/NativeScript/issues/4041#issuecomment-465477508

So for the time being I'm not going to take any actions on fixing this, until the core team decides how will they proceed with this. Will leave the issue open until then.

**Comment by PeterStaev** [comment]
This is now available in the new version of the plugin available in the [ProPlugins NPM](https://npm.proplugins.org) registry. The code uses the new `@nativescript` scoped packages. 

All future work of this plugin will be available exclusively as part of ProPlugins initiative. So if you want to get the latest updates/fixes/features make sure you [subscribe to the service](https://proplugins.org/subscribe.html). You get all my plugins plus many of the most used and high quality plugins for a small monthly subscription fee.
