### ISSUE TITLE
On iOS the photo editor does not open full screen

### ISSUE THREAD

**Issue by amarseelam** [PeterStaev/nativescript-photo-editor#28]
On iOS the photo editor does not open full screen,  And the photo editor starts to move up and down when using the pen tool.
How can I make the photo editor occupy  the whole screen?
![Screen Shot 2019-10-15 at 6 37 40 AM](https://user-images.githubusercontent.com/12731237/66824605-9cc53680-ef16-11e9-9ca9-66797e4ff96c.png)

**Comment by Serge-SDL** [comment]
Hi! @PeterStaev 
got the same issue and it's very annoying because it makes the plugin unusable on ios 13 (and 79% of iOS user are now on 13 verison).
can you take a look ? can I help on something (unfortunately I dont know IOS languages, but I know nativescript :) )

thanks!

**Comment by Lelelo1** [comment]
I found a solution:
The ViewController's [modalPresentationStyle](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621355-modalpresentationstyle) had to be set to [automatic](https://developer.apple.com/documentation/uikit/uimodalpresentationstyle).

(in js):
```
    /* ... */
    viewController.photoEditorDelegate = _this._delegate;
    viewController.modalPresentationStyle = 0; // <--- here
    frame.topmost().ios.controller.presentViewControllerAnimatedCompletion(viewController, true, null);
```

**Comment by PeterStaev** [comment]
This is now available in the new version of the plugin available in the [ProPlugins NPM](https://npm.proplugins.org) registry. 

All future work of this plugin will be available exclusively as part of ProPlugins initiative. So if you want to get the latest updates/fixes/features make sure you [subscribe to the service](https://proplugins.org/subscribe.html). You get all my plugins plus many of the most used and high quality plugins for a small monthly subscription fee.

**Comment by Serge-SDL** [comment]
Hi @PeterStaev !
I subsriebed to the ProPlugins NPM registry but I can't install it. I let a message on there https://git.proplugins.org/Tangra/nativescript-photo-editor/issues/1 but got no answer :(
I really need the plugin for my clients... can you help me ?
thanks

**Comment by PeterStaev** [comment]
@Serge-SDL , I've responded to your issue in the ProPlugins repo. Please check it out.
