### ISSUE TITLE
Does not seem to launch in iOS from a modal page.

### ISSUE THREAD

**Issue by throwingdarts** [PeterStaev/nativescript-photo-editor#6]
I created an app where a photo detail view opens in a modal along with a button to edit using this editor. All works as expected in android but can't get editor to launch in iOS from the modal. When I change to a standard page (not modal) everything works as expected.

**Comment by PeterStaev** [comment]
The editor itself is a modal. And since you cannot have more than one modal under iOS, there is nothing that can be done. So you have to use different layouts so that you do not have nested modals.

**Comment by throwingdarts** [comment]
That makes sense. Thanks.
